export * from "./announces-ctrl.type"
export * from "./artists-ctrl.type"
export * from "./auth-ctrl.type"
export * from "./events-ctrl.type"
export * from "./records-ctrl.type"
export * from "./songs-ctrl.type"
export * from "./labels-ctrl.type"
